name: TimeSignal
version: '1.0.0'
main: com.hinaplugin.timeSignal.TimeSignal
api-version: '1.21'
authors: [ hina2113 ]
description: 時報をプレイヤーに送信する

commands:
  timesignal:
    permission: timesignal.command

permissions:
  timesignal.command:
    description: "config.yml reload"
    default: op
  timesignal.notice:
    description: "TimeSignal notice received."
    default: true
  
